spring:
  application:
    name: pms
  datasource:
    url: jdbc:mysql://localhost:3306/pmsDB?createDatabaseIfNotExist=true
    username: root
<<<<<<< HEAD
    password: Obese/towny5
=======
    password: Incide+koil8
>>>>>>> baeb7ea183c1091ddc5571806b89b84de0cc64c3
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    
  mail:
    host:
    port: 1025
    username: user
    password: user
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connection-timeout: 5000
        timeout: 3000
        write-timeout: 5000
        
  activemq:
    broker-url:tcp: http://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: false
      trusted:
        - com.thewinningteam.pms.message
        - java.time  # Trust java.time for LocalDateTime serialization
        
application:
  security:
    jwt:
      secret-key: p8gttsnjdpgvh29fgxsdghf58c05a0tykadogghxhbgyv0d6em7rll
      expiration: 86400000
      
  mailing:
    frontend:
      activation-url: http://localhost:5173/activate-account

  jackson:
    serialization:
      write_dates_as_timestamps: false

      
      
