spring:
  application:
    name: pms
  datasource:
    url: jdbc:mysql://localhost:3306/pmsDB?createDatabaseIfNotExist=true
    username: root
    password: 7545590000
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    
  mail:
    host:
    port: 1025
    username: user
    password: user
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connection-timeout: 5000
        timeout: 3000
        write-timeout: 5000
        
application:
  security:
    jwt:
      secret-key: p%=&tsn^dp#vh29^g&s*%f58c05a0^&kado#%xhb#yv0)6em7@=
      expiration: 86400000
      
  mailing:
    frontend:
      activation-url: http://localhost:5173/activate-account
      
      
